name: 27 Station
favicon: null
layout_spectrum: 1
typography_spectrum: 0.30884
title: Gift Shop · Arts & Crafts Supply Store · Men's Clothing Store
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f8d11f'
    - '#443e3e'
    - '#000000'
    - '#a08714'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
