name: 27 Station
favicon: null
layout_spectrum: 1
typography_spectrum: 0.30884
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f8d11f'
    - '#443e3e'
    - '#000000'
    - '#a08714'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
