name: 27 Station
favicon: null
layout_spectrum: 0.8403136094566435
typography_spectrum: 0.8676782434340566
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.42551922076381743
  lightness: 0.12256709253415465
  saturation: 0.8485156919341534
  rhythmicContrast: 0.6823968854732811
purpose: []
