title: Gift Shop · Arts & Crafts Supply Store
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 0.5
  lightness: 0.5
  brandColors:
    - '#FFFFFF'
    - '#F8D11E'
    - '#000000'
    - '#989898'
    - '#333333'
  rhythmicContrast: 0.5
cta:
  bucket: null
  version: null
  domain: null
name: 27 Station
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.30884
layout_spectrum: 0.460371
